version: "3"
services:
  redis:
    image: redis:6.2
    container_name: local-redis-dev
    ports:
      - "6379:6379"
  mysql:
    image: mysql:8
    container_name: local-mysql-dev
    environment:
      - MYSQL_ROOT_PASSWORD=qwer1234
      - MYSQL_DATABASE=public
    ports:
      - "3306:3306"
    # platform: linux/x86_64
