version: "3"
services:
  ###############
  # MYSQL
  ###############
  mysql:
    platform: linux/x86_64
    image: mysql:8
    container_name: local-mysql-dev
    environment:
      - MYSQL_ROOT_PASSWORD=qwer1234
      - MYSQL_DATABASE=public
    ports:
      - "3306:3306"

    command: --innodb_ft_min_token_size=1

  
  ###############
  # REDIS as message broker
  ###############
  redis-message-broker:
    platform: linux/x86_64
    image: redis:6.2
    container_name: redis-message-broker
    ports:
      - 6399:6379


  ###############
  # REDIS
  ###############
  redis-cluster:
    platform: linux/x86_64
    image: redis:6.2
    container_name: local-redis-dev
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6380:6380
      - 6381:6381
      - 6379:6379

  redis-node-1:
    network_mode: "service:redis-cluster"
    platform: linux/x86_64
    image: redis:6.2
    container_name: local-redis-dev1
    volumes:
      - ./docker/redis/redis1.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-node-2:
    network_mode: "service:redis-cluster"
    platform: linux/x86_64
    image: redis:6.2
    container_name: local-redis-dev2
    volumes:
      - ./docker/redis/redis2.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-cluster-entry:
    network_mode: "service:redis-cluster"
    platform: linux/x86_64
    image: redis:6.2
    container_name: local-redis-cluster-entry
    command: redis-cli --cluster create 127.0.0.1:6379 127.0.0.1:6380 127.0.0.1:6381 --cluster-yes
    depends_on:
      - redis-cluster
      - redis-node-1
      - redis-node-2
