on:
  pull_request:
    branches: [master, staging, dev]
name: Continous Integration Workflow
jobs:
  Lint:
    name: Lint Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Dependencies
        uses: bahmutov/npm-install@v1 # install dependencies using cache
      - name: Check Lint all affected apps and libs
        run: yarn affected:lint --base="origin/${GITHUB_BASE_REF}"
  Test:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Dependencies
        uses: bahmutov/npm-install@v1 # install dependencies using cache
      - name: Run tests all affected apps and libs
        run: yarn affected:test --base="${GITHUB_REF}"
  # e2eTest:
  #   name: E2ETest Job
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1
  #     - name: Install Dependencies
  #       uses: bahmutov/npm-install@v1 # install dependencies using cache
  #     - name: Run e2e tests all affected apps and libs
  #       run: yarn affected:e2e --base="${GITHUB_BASE_REF}"
  Build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Dependencies
        uses: bahmutov/npm-install@v1 # install dependencies using cache
      - name: Run Build all affected apps and libs
        run: yarn affected:build --base=${{ github.event.pull_request.base.ref }}


