on:
  pull_request:
    branches: [master, staging, dev]

name: Continous Integration Workflow
jobs:
  Lint:
    name: Lint Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
      - name: Check Lint all affected apps and libs
        run: yarn affected:lint --base="origin/${GITHUB_BASE_REF}"
  Test:
    name: Test Job
    runs-on: ubuntu-latest
    env:
      MYSQL_DATABASE: test_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      DATABASE_URL: mysql://root:root@localhost/test_db
      JWT_SECRET: JWT_SECRET
    steps:
      - name: Setup MySQL
        run: |
          sudo systemctl start mysql.service
          mysql -e 'CREATE DATABASE ${{ env.MYSQL_DATABASE }};' -u${{ env.MYSQL_USER }} -p${{ env.MYSQL_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Dependencies
        uses: bahmutov/npm-install@v1 
      - name: Primsa generate # Generate Prisma Client
        run: yarn nx run prisma-orm:prisma-generate
      - name: Prisma Migrate # Migrate Prisma Schema to DB
        run: yarn nx run prisma-orm:migrate-dev
      - name: Run tests all affected apps and libs
        run: yarn affected:test --base="origin/${GITHUB_BASE_REF}"
  # e2eTest:
  #   name: E2ETest Job
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1
  #     - name: Install Dependencies
  #       uses: bahmutov/npm-install@v1
  #     - name: Run e2e tests all affected apps and libs
  #       run: yarn affected:e2e --base="origin/${GITHUB_BASE_REF}"
  Build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
      - name: Primsa generate # Generate Prisma Client
        run: yarn nx run prisma-orm:prisma-generate
      - name: Run Build all affected apps and libs
        run: yarn affected:build --base="origin/${GITHUB_BASE_REF}"


