on:
  pull_request:
    branches: [master, staging, dev]
name: Continous Integration Workflow
jobs:
  Lint:
    name: Lint Job
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Dependencies
        uses: bahmutov/npm-install@v1 # install dependencies using cache
      - name: Check Lint all affected apps and libs
        run: yarn affected:lint --base=${{ steps.extract_branch.outputs.branch }}
  Test:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Dependencies
        uses: bahmutov/npm-install@v1 # install dependencies using cache
      - name: Run tests all affected apps and libs
        run: yarn affected:test --base=${{ steps.extract_branch.outputs.branch }}
  # e2eTest:
  #   name: E2ETest Job
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Extract branch name
  #       shell: bash
  #       run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
  #       id: extract_branch
  #     - name: Checkout
  #       uses: actions/checkout@v1
  #     - name: Install Dependencies
  #       uses: bahmutov/npm-install@v1 # install dependencies using cache
  #     - name: Run e2e tests all affected apps and libs
  #       run: yarn affected:e2e --base=${{ steps.extract_branch.outputs.branch }}
  Build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Dependencies
        uses: bahmutov/npm-install@v1 # install dependencies using cache
      - name: Run Build all affected apps and libs
        run: yarn affected:build --base=${{ steps.extract_branch.outputs.branch }}


